# Generated by Django 2.1.5 on 2019-02-08 15:36

from django.conf import settings
from django.db import migrations, models
import specials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=models.SET(specials.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
