# Generated by Django 2.1.7 on 2019-03-19 18:20

from django.conf import settings
from django.db import migrations, models
import specials.models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0002_fib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fib',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(specials.models.get_sentinel_user), related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
