# Generated by Django 2.1.7 on 2019-02-15 09:43

from django.conf import settings
from django.db import migrations, models
import tholisa.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tholisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=models.SET(tholisa.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
